### ISSUE TITLE
Can't put the mod inside another folder in BepInEx/plugins

### ISSUE THREAD

**Issue by PurplefinNeptuna** [hisacat/RF5.HisaCat.NPCDetails#1]
I usually put plugin files inside its own folder inside `BepInEx/plugins` so It doesn't look messy.
![image](https://user-images.githubusercontent.com/23467102/185014979-0fa7fad7-eee5-47f8-8ee9-655c574a0ee2.png)

The reason I put it that way because:
1. It looks cleaner
2. Some mods required the same dlls (e.g. Newtonsoft.Json) which make confusion/error if it is different.

But it seems to cause error when I put your mod inside a folder (In image above I put it in `NPCDetails` folder).

Error Log:
```
[Error  :NPCDetails] [RF5.HisaCat.NPCDetails] BundleLoader: Bundle missing. bundle must be placed at "D:\Program Files (x86)\Steam\steamapps\common\Rune Factory 5\BepInEx\plugins\RF5.HisaCat.NPCDetails\npcdetails.main.unity3d"
```
Which means I can't put the mod inside a folder with other name than your `GUID`.

From what I can see from the code:
https://github.com/hisacat/RF5.HisaCat.NPCDetails/blob/790aefdb9e483ea937b531c7473724a563a3b636/BundleLoader.cs#L23
https://github.com/hisacat/RF5.HisaCat.NPCDetails/blob/2d46c784e2c90cfb0e69db889d52fda5113a2f5d/Localization/LocalizationManager.cs#L66
https://github.com/hisacat/RF5.HisaCat.NPCDetails/blob/2d46c784e2c90cfb0e69db889d52fda5113a2f5d/Localization/LocalizationManager.cs#L87
You are using `Paths.PluginPath` which gives only `BepInEx\plugins` path,
So I recommend you to instead use:
```cs
System.IO.Path.GetDirectoryName(IL2CPPChainloader.Instance.Plugins[GUID].Location)
```
as this will give your plugin dll folder locations.

Currently I can mitigate the problem by moving `RF5.HisaCat.NPCDetails.dll` and `Newtonsoft.Json.dll` inside `RF5.HisaCat.NPCDetails` folder

**Comment by hisacat** [comment]
Thanks for suggestion about this issue :)
I also just saw posts with related about this issue on your mod from Nexus few hours ago.
100% agree about your suggestion and I'll apply this asap. thanks

**Comment by hisacat** [comment]
Applied at [v1.3.1](https://github.com/hisacat/RF5.HisaCat.NPCDetails/releases/tag/v1.3.1)
Thanks XD
